package vu.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.mybatis.model.Cat;
import vu.mybatis.model.Owner;
import vu.mybatis.model.Shelter;

@Mapper
public interface CatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAT
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAT
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    int insert(Cat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAT
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    Cat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAT
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    List<Cat> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAT
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    int updateByPrimaryKey(Cat record);
}