package vu.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.mybatis.model.CatOwner;

@Mapper
public interface CatOwnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAT_OWNER
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    int insert(CatOwner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAT_OWNER
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    List<CatOwner> selectAll();
}