package vu.mybatis.model;

import java.util.List;

public class Cat {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAT.ID
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAT.AGE
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAT.NAME
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAT.OPT_LOCK_VERSION
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    private Integer optLockVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAT.SHELTER_ID
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    private Integer shelterId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAT.ID
     *
     * @return the value of PUBLIC.CAT.ID
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAT.ID
     *
     * @param id the value for PUBLIC.CAT.ID
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAT.AGE
     *
     * @return the value of PUBLIC.CAT.AGE
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAT.AGE
     *
     * @param age the value for PUBLIC.CAT.AGE
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAT.NAME
     *
     * @return the value of PUBLIC.CAT.NAME
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAT.NAME
     *
     * @param name the value for PUBLIC.CAT.NAME
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAT.OPT_LOCK_VERSION
     *
     * @return the value of PUBLIC.CAT.OPT_LOCK_VERSION
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    public Integer getOptLockVersion() {
        return optLockVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAT.OPT_LOCK_VERSION
     *
     * @param optLockVersion the value for PUBLIC.CAT.OPT_LOCK_VERSION
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    public void setOptLockVersion(Integer optLockVersion) {
        this.optLockVersion = optLockVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAT.SHELTER_ID
     *
     * @return the value of PUBLIC.CAT.SHELTER_ID
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    public Integer getShelterId() {
        return shelterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAT.SHELTER_ID
     *
     * @param shelterId the value for PUBLIC.CAT.SHELTER_ID
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    public void setShelterId(Integer shelterId) {
        this.shelterId = shelterId;
    }

    // Added manually
    private Shelter shelter;
    private List<Owner> owners;
}