package vu.mybatis.model;

public class Shelter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHELTER.ID
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHELTER.TITLE
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHELTER.ID
     *
     * @return the value of PUBLIC.SHELTER.ID
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHELTER.ID
     *
     * @param id the value for PUBLIC.SHELTER.ID
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHELTER.TITLE
     *
     * @return the value of PUBLIC.SHELTER.TITLE
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHELTER.TITLE
     *
     * @param title the value for PUBLIC.SHELTER.TITLE
     *
     * @mbg.generated Sun Mar 21 13:01:16 EET 2021
     */
    public void setTitle(String title) {
        this.title = title;
    }
}